server:
  port: 8080

# datasource
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/help_desk?createDatabaseIfNotExist=true&useSSL=false
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: root

  # jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
